### ISSUE TITLE
Subcommand alias feature like 'git config alias.foo bar'

### ISSUE THREAD

**Issue by AvianY** [vim-volt/volt#232]
I think the volt commands would be more consistent with following ideas:

Instead of `$volt get -u` for updating, there could be a separate command like `$volt update`

The `$volt get` command as of now, downloads **and** enables the plugins. So basically it does the same as the command `$volt enable`, but it also downloads the plugin if it doesn't exist. Instead of that, the `$volt get` command could just download the plugin without enabling it. But if the user wants to enable it at the same time, he could just write something like `$volt get -e <repo>` (-e for enable).

what do you think?

**Comment by tyru** [comment]
> Instead of $volt get -u for updating, there could be a separate command like $volt update

`volt get -u` guarantees given plugins exist and are updated to the latest with no error.
it installs if not installed, and updates to the latest.

hmm, isn't it enough to add command alias feature like `git config alias.update get -u`?

> The $volt get command as of now, downloads and enables the plugins. 

hmm, if I try to add enable/diasble control option, I'll add `-no-enable` option (don't add specified plugins to current profile).
Because profile feature is optional, user can use it but also can choose not to use it.
If `volt get foo/bar` is not enabled (not added to current profile), user are confused if he/she does not know profile feature.

**Comment by AvianY** [comment]
If there was an alias feature, it would be the great, yes. Users can then
modify commands to their liking.

**Comment by tyru** [comment]
Okay, I edited the title :)

**Comment by tyru** [comment]
I have implemented this feature in devel branch.
You can write the following to config.toml:

```toml
[alias]
update = ["get", "-u"]
```

And

```
$ volt update foo/bar.vim
```
